### ISSUE TITLE
[🤝🏽 Reunião] Brainstorming da equipe

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#240]
## [Reunião: Brainstorming - Hub Design e Comunicação](meet.google.com/rwe-zxfd-ozg)

📅 **Data:** 04/06/2024
🕒 **Horário:** 19h às 20h

📝 **Pauta:** 
-Avaliar o planejamento para o Polo Maceió (o que funcionou bem, o que precisa melhorar)
-Checar o "pós-evento" do Polo Maceió
-Recuperar agenda de conteúdos nas redes
-Planejar campanha para o Polo Campina Grande

👥 **Participantes:** 
Jaline Mombach @jalinegm 
Prof. Poty Lucena @RedeDSBR 
Joyce Araujo @joy-araujo 
Lucas Rafiki @lucrafi22 
Tamires Barreto @Tamiresbarretoo 

### 📝 Resumo:

**1. Avaliação das estratégias de comunicação para o evento do Polo Maceió**
Pontos Positivos:
-contagem regressiva para o evento
-avisos por meio das redes sociais (como troca do local)
-layout para fotos já no Canva

Pontos a Melhorar:
-muitas dúvidas para saber se a inscrição havia sido efetivada
-dúvidas em relação às cidades participantes
-melhorar o planejamento dos conteúdos durante o evento
-melhorar a comunicação com a equipe que estiver no evento

Lucas também mencionou que é importante pensar em um "escriba" ou alguém para registrar as perguntas e comentários dos participantes.

**2. "Pós-evento" do Polo Maceió:**
-utilizar os registros que estão no [álbum compartilhado](https://photos.google.com/share/AF1QipPZO3HknXaYiapVAyQuyoTEM-7b9OL86huOKmFc2dwvlej2ZIiOcEEMCCioIRXZCA?key=Y0JYSlVyRUJDMV9mUzZ6eUZEQ2JjM3VDMnRzODhB) para criar um vídeo ou post relembrando o evento.
-as avaliações do evento também podem ser uma fonte para postagem

**3. Atualização do calendário de conteúdo para garantir postagens regulares.**
Joyce e Tamires relataram que estavam trabalhando em postagens para o perfil da DSBR. Prof. Poty indicou que nesse momento o foco maior é o CecateNe e que em agosto o CecateNe terá uma pausa e então, o perfil da Rede DSBR ficará em evidência novamente. Entretanto, comentou que no próximo dia 24 de junho estará indo para o [I Congreso Internacional Estado Abierto y Gobernanza](https://www.congresoestadoabierto.una.ac.cr/102260/section/50621/i-congreso-internacional-de-estado-abierto-y-gobernanza.html), na Costa Rica. Logo, é uma oportunidade para movimentar as redes sociais da DSBR.

**4. Planejamento da Campanha para o Polo Campina Grande**
Tamires falou da importância de termos uma caixa para dúvidas e perguntas antes do evento, além da mensagem de confirmação no formulário de inscrição.  Também, pensaram em publicar um tutorial sobre como se inscrever. Discutiu-se a possibilidade de pensar em um conteúdo que explique o conceito de polos do CecateNe, assim como consta no site "Propomos no plano de trabalho a criação de 42 Polos Territoriais de Formação do Transporte Escolar que foram distribuídos considerando o agrupamento de municípios em regiões intermediárias da região Nordeste (IBGE)". Muitas dúvidas surgiram sobre quais cidades estavam contempladas no Polo Maceió, por isso, um post nas redes falando sobre as cidades poderia ajudar.

O Prof. Poty salientou a importância de prever as ações, deixar tudo pronto para só alterar no momento do evento. Inclusive, as orientações sobre o quê e como gravar/captar fotos para a equipe de apoio local. Também, planejar os depoimentos e as parcerias com Uncme, Undime, Prefeituras, na ideia de "trabalharmos juntos". Já começar a registrar o evento ocorrendo desde o credenciamento, bem como, todas as demais atividades da programação - olhar a programação com antecedência.
Sugeriu olharmos a cobertura do evento do Fórum Regional Sul da Undime (https://www.instagram.com/undimenacional/).
 
Prof. Poty exemplificou os últimos dois vídeos postados no instagram, sobre a diferença entre eles: uma pergunta no início do vídeo. O efeito surpresa é primordial para engajamento nas redes. Nesse sentido, poderia se pensar em "Qual será o próximo Polo?". Além disso, destacou a necessidade de estudarmos a cultura nordestina, o jeito nordestino (sem clichês globais) e que as melhores ideias estão nos comentários das postagens. Nesse sentido, Lucas falou de um tipo de postagem de adivinhação, colocando fotos do lugar como pistas. O Prof. Poty indicou que Campina Grande tem "o maior São João do Mundo" e sugeriu estudo sobre [Biliu de Campina](https://www.youtube.com/watch?v=Hgdd4YLtLwY)

### 🚀 Encaminhamentos:

- [x] @joy-araujo fará  #238 
- [x] @Tamiresbarretoo criará conteúdo de "memória" (TBT?) do evento de Maceió para postagem (checar avaliações e o [álbum compartilhado](https://photos.google.com/share/AF1QipPZO3HknXaYiapVAyQuyoTEM-7b9OL86huOKmFc2dwvlej2ZIiOcEEMCCioIRXZCA?key=Y0JYSlVyRUJDMV9mUzZ6eUZEQ2JjM3VDMnRzODhB))
- [x] @jalinegm adaptará o formulário de inscrição para mostrar todas as cidades e também a confirmação final de inscrição
- [x] @jalinegm colocará um trecho para autorização de exibição de imagem "Ao se inscrever no evento você concorda com  a captação de sua imagem/vídeo para divulgação do evento nas redes sociais do CecateNe"
- [x] @jalinegm pedirá atualização do site para Gabriel (retirar postagens antigas do Polo Maceió)
- [ ] Criar postagem na DSBR sobre o [I Congreso Internacional Estado Abierto y Gobernanza](https://www.congresoestadoabierto.una.ac.cr/102260/section/50621/i-congreso-internacional-de-estado-abierto-y-gobernanza.html), na Costa Rica. Prof. Poty participará da sessão Enseñanzas del gobierno Abierto desde Brasil (Lições do Governo Aberto no Brasil) na programação de mesas do dia 27 de junho: https://www.congresoestadoabierto.una.ac.cr/102260/section/51005/i-congreso-internacional-de-estado-abierto-y-gobernanza.html
- [x] Acompanhar cobertura do evento do Fórum Regional Sul da Undime (https://www.instagram.com/undimenacional/)
- [ ] Criar caixas de dúvidas sobre o evento #241 
- [x] Elaborar postagem para adivinhar qual o próximo polo #241 
- [x] Criar tutorial de inscrição #241 
- [x] Criar card sobre a organização de polos do CecateNe (explicando que serão 42) #241 
- [ ] Criar card sobre os municípios que fazem parte do Polo Campina Grande #241 
- [x] Planejar as postagens para publicação durante o evento (deixar templates prontos, usando outras fotos/vídeos e só substituir depois) - #241 
- [x] Criar roteiro com "orientações" para o tipo de mídia desejada para a equipe que estará no evento #241 

![image](https://github.com/Rede-DSBR/CecateNE/assets/37112456/4dea9ce2-0724-41e2-b1f3-7eb2c63f162e)
